Check for exit code of update creation

diff --git a/.appveyor.yml b/.appveyor.yml
--- a/.appveyor.yml
+++ b/.appveyor.yml
@@ -252,6 +252,10 @@ after_build:
           cd $PARENT_DIR
           mkdir "$PARENT_DIR\$ELMAVEN_UPDATES"
           repogen.exe -p packages -i com.vendor.product "$PARENT_DIR\$ELMAVEN_UPDATES"
+          if ( $? -eq $false ) {
+              echo 'Failed to create update archive for release.'
+              exit 1
+          }
 
           echo "Pushing update repository for $ELMAVEN_BRANCH ..."
           cd "$PARENT_DIR\$ELMAVEN_UPDATES"
@@ -261,7 +265,11 @@ after_build:
           git add .
           git commit -m "[Windows] Update archives for $ELMAVEN_BRANCH"
           git remote add origin "https://${env:BB_USER}:${env:BB_APP_PASS}@bitbucket.org/saifulbeekhan/elmaven-updates.git"
-          git push --force origin master:${UPDATE_BRANCH}
+          git push --force origin master:${UPDATE_BRANCH} 2>&1 | write-host # send push output to stdout instead of stderr
+          if ( $? -eq $false ) {
+              echo 'Failed to push update repository for release.'
+              exit 1
+          }
 
           # create installer
           echo "Creating installer ..."
diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -238,6 +238,10 @@ after_success:
         cd $PARENT_DIR
         mkdir "$PARENT_DIR/$ELMAVEN_UPDATES"
         $INSTALLER_TOOLS_DIR/repogen -p packages -i com.vendor.product "$PARENT_DIR/$ELMAVEN_UPDATES"
+        if [ $? != 0 ]; then
+          echo "Failed to create update archive for release."
+          exit 1
+        fi
 
         echo "Pushing update repository for $ELMAVEN_BRANCH ..."
         cd "$PARENT_DIR/$ELMAVEN_UPDATES"
@@ -248,6 +252,10 @@ after_success:
         git commit -m "[MacOS] Update archives for $ELMAVEN_BRANCH"
         git remote add origin "https://$BB_USER:$BB_APP_PASS@bitbucket.org/saifulbeekhan/elmaven-updates.git"
         git push --force origin master:$UPDATE_BRANCH
+        if [ $? != 0 ]; then
+          echo "Failed to push update repository for release."
+          exit 1
+        fi
       fi
 
       # create installer
